removed queryRenderedFeatures which had errors: index.d.ts(259,31): error TS7006: Parameter 'options' implicitly has an 'any' type. index.d.ts(259,63): error TS2314: Generic type 'Promise<T>' requires 1 type argument(s).